config/routes.rb
Demo::Application.routes.draw do
  resources :users

  get '/search' => 'pages#search'

  resource :session

  get 'auth/facebook/callback' => 'sessions#create'

  root to: 'pages#search'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :user_id

  include PgSearch
  multisearchable against: [:title, :body]


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :avatar, :uid

  has_attached_file :avatar

  has_many :posts

  include PgSearch
  pg_search_scope :search_on_name, against: [:name, :email]
  multisearchable against: [:name, :email]



  def self.find_by_credentials(creds)
    if creds[:email] && creds[:password]
      User.where(email: creds[:email], password: creds[:password])[0]
    end
  end

  def self.create_from_fb_data(fb_data)
    User.create!(uid: fb_data[:uid])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :signed_in?, :current_user

  def signin_user(user)
    @current_user = user
    session[:user_id] = user.id
  end

  def current_user
    return nil unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def signed_in?
    !!current_user
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def search
    if params[:query]
      @results = PgSearch.multisearch(params[:query])
    else
      @results = PgSearch::Document
    end

    @results = @results.includes(:searchable).page(params[:page])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if request.env['omniauth.auth']
      fb_data = request.env['omniauth.auth']
      @user = User.find_by_uid(fb_data[:uid])

      unless @user
        @user = User.create_from_fb_data(fb_data)
      end

    else
      @user = User.find_by_credentials(params[:user])
    end

    if @user
      signin_user(@user)
      redirect_to @user, notice: "Successfully logged in"
    else
      flash.now[:alert] = "Bad username/password combo."
      render :new
    end
  end

  def destroy
    signout!
    redirect_to root_url, notice: "Successfully logged you out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:posts).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
You are <%= link_to current_user.email, current_user %>
<% else %>
<%= link_to "Sign in!", new_session_url %>
<% end %>

<br><hr>

<%= yield %>

</body>
</html>

app/views/pages/search.html.erb
<div>
  <form action="<%= root_url %>" method="GET">
    <!-- ########## Notice we don't need the authenticity ######## -->
    <!-- ########## token because this is a GET request   ######## -->

    <input type="text" name="query" value="<%= params[:query] %>">
    <input type="submit" value="Search!">
  </form>

  <br>

  <%= paginate @results %>
  <br>

  <%= render @results.map(&:searchable) %>
</div>

app/views/posts/_post.html.erb
<div>
  <h2><%= post.title %></h2>
  <p><%= post.body %></p>
</div>

app/views/users/_form.html.erb
<% action = @user.persisted? ? user_url(@user) : users_url %>
<% button_msg = @user.persisted? ? "Save changes" : "Persist!" %>

<form action="<%= action %>" method="POST" enctype="multipart/form-data">

  <% if @user.persisted? %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>

  <input type="hidden" name="authenticity_token"
                      value="<%= form_authenticity_token %>">

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited this
        user from being saved:
      </h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="user_username">Username</label><br>
    <input type="text" id="user_username"
                     name="user[username]" value="<%= @user.username %>">
  </div>

  <div class="field">
    <label for="user_avatar">Avatar</label><br>
    <input type="file" id="user_avatar" name="user[avatar]">
  </div>

  <div class="actions">
    <input type="submit" value="<%= button_msg %>">
  </div>
</form>

app/views/users/_user.html.erb
<div>
  <%= user.name %>
  <%= user.email %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Users</th>
    <th>Posts</th>
    <th></th>
    <th></th>
  </tr>

<%= link_to 'previous', users_url(page: @users.current_page - 1) %>
| <%= @users.current_page %> |
<%= link_to @users.current_page + 1, users_url(page: @users.current_page + 1) %>

<% @users.each do |user| %>
  <tr>
    <td>
      <%= link_to user.name, user %> | <%= mail_to user.email, user.email %>
    </td>
    <td><%= user.posts.length %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= paginate @users %>
<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @user.avatar.url %>

<p>
  <b>Username:</b>
  <%= @user.email %>
</p>

<h2>Posts</h2>
<% @user.posts.each do |post| %>
<article>
  <header><strong><%= post.title %></strong></header>
  <p><%= post.body %></p>
</article>
<% end %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>